version: '3.7'
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ticket
    container_name: ticket-apps
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - './:/var/www'
    depends_on:
      - db
      - nginx
    networks:
      - ticket-app

  db:
    image: mysql:5.6.47
    container_name: ticket-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ticket-volume:/var/lib/mysql
    networks:
      - ticket-app

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: ticket-php-admin
    restart: unless-stopped
    ports:
      - '8088:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - ticket-app

  nginx:
    image: nginx:alpine
    container_name: ticket-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - ticket-app

networks:
  ticket-app:
    driver: bridge

volumes:
  ticket-volume:
