<?php

namespace App\Repositories;

use App\Models\Payment;
use JasonGuru\LaravelMakeRepository\Repository\BaseRepository;
//use Your Model

/**
 * Class PaymentRepository.
 */
class PaymentRepository extends BaseRepository
{
    /**
     * @return string
     *  Return the model
     */
    public $PAY_SUCCESS = '1';

    public function model()
    {
        return Payment::class;
    }

    public function getPaymentUser($orderId) {
        return Payment::where('order_id',$orderId)->get();
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
