<?php

namespace App\Repositories;

use App\Models\Payment;
use JasonGuru\LaravelMakeRepository\Repository\BaseRepository;
//use Your Model

/**
 * Class PaymentRepository.
 */
class PaymentRepository extends BaseRepository
{
    /**
     * @return string
     *  Return the model
     */
    public $PAY_SUCCESS = '1';

    public function model()
    {
        return Payment::class;
    }

    public function getPaymentUser($orderId) {
        return Payment::where('order_id',$orderId)->get();
    }

    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function payUsersOrder($id) {
        return \DB::table('payments')
            ->join('orders', 'orders.id','=', 'payments.order_id')
            ->join('tickets', 'tickets.id', '=', 'orders.ticket_id')
            ->join('users', 'users.id', '=', 'orders.user_id')
            ->where('users.id', auth()->user()->id)
            ->where('orders.id', $id)
            ->select('payments.id',
                    'tickets.from', 'tickets.to',
                    'payments.sum_price', 'payments.bank_id',
                    'payments.code_fixed', 'tickets.time',
                    'orders.ticket_count', 'users.name', 'payments.url_barcode')
            ->first();
    }
}
